using System;

namespace Disassembler
{
    internal enum CliMetadataToken
    { 
        Module                 = 00,
        TypeRef                = 01,
        TypeDef                = 02,
        FieldPtr               = 03,
        Field                  = 04,
        MethodPtr              = 05,
        MethodDef              = 06,
        ParamPtr               = 07,
        Param                  = 08,
        InterfaceImpl          = 09,
        MemberRef              = 10,
        Constant               = 11,
        CustomAttribute        = 12,
        FieldMarshal           = 13,
        DeclSecurity           = 14,
        ClassLayout            = 15,
        FieldLayout            = 16,
        StandAloneSig          = 17,
        EventMap               = 18,
        EventPtr               = 19,
        Event                  = 20,
        PropertyMap            = 21,
        PropertyPtr            = 22,
        Property               = 23,
        MethodSemantics        = 24,
        MethodImpl             = 25,
        ModuleRef              = 26,
        TypeSpec               = 27,
        ImplMap                = 28,
        FieldRva               = 29,
        ENCLog                 = 30,
        ENCMap                 = 31,
        Assembly               = 32,
        AssemblyProcessor      = 33,
        AssemblyOS             = 34,
        AssemblyRef            = 35,
        AssemblyRefProcessor   = 36,
        AssemblyRefOS          = 37,
        File                   = 38,
        ExportedType           = 39,
        ManifestResource       = 40,
        NestedClass            = 41,
        GenericParam           = 42,
        MethodSpec             = 43,
        GenericParamConstraint = 44,
    }
}